### ISSUE TITLE
cooccurrence_matrices/absolute lists wrong SNP

### ISSUE THREAD

**Issue by ibseq** [dorbarker/voc-identify#41]
Hi DIllon, 
I noticed in the cooccurrence_matrices/absolute path that one of the variants has a SNP that is not listed in the mutations.tsv file: specifically , the location is correct but the nucleotide change is wrong: how is this possible and how can I troubleshoot it? I checked many times and re-run it many times. I'm assuming is listed wrong in al other output files

thanks
ibseq

**Comment by dorbarker** [comment]
Thanks for the bug report. I will look into it.

Could you provide a copy of the mutations file and the cooccurence matrix? You should be able to attach it here, or paste them into gist.github.com

**Comment by ibseq** [comment]
Hi Dillon
any update? - Sent you the two files privately

thanks
ibseq

**Comment by dorbarker** [comment]
Apologies - I was on vacation. I'm back to work on mmmvi now. 

However, I don't see any files in my email nor linked anywhere on github.

**Comment by ibseq** [comment]
Hi Dillon
Apologies and hope you had a nice  rest. 

If I remove one of the variants, it runs fine…not sure why. 

Here’s the mail I sent time ago: I’ve since then run it many times by simply not including one variant ….

> Begin forwarded message:
> 
> From: "irene z.b." ***@***.***>
> Subject: Re: [dorbarker/voc-identify] cooccurrence_matrices/absolute lists wrong SNP (#41)
> Date: 14 July 2021 at 19:59:07 BST
> To: Author ***@***.***>
> 
> Hi Dillon
> See attached. This is just one samples out of many - they all have same issue. I only looked at 23102 but not sure if other positions have been affected. Can you please not publish the data in the attached file?
> 
> Thanks
> 
> BW
> Irene
> 
>

**Comment by dorbarker** [comment]
Hmm. Weirdly enough, I don't see it - not even accidentally diverted to spam. Sorry about that. Could I trouble you to send it again?

**Comment by ibseq** [comment]
Hi Dillon
Will you be able to help with the error below? Snakelike worked only on s bunch of bam file within folder. Tried to run the single samples and got this: - 

(mmmvi) ***@***.***:~/MMMVI/LIV_SAMPLES$ mmmvi --bam bams/7601_2107902_09_S31.mapped.primertrimmed.sorted.bam --reference data/reference.fasta --mutations data/mutations.tsv --outdir reports/7601_2107902_09_S31.mapped.primertrimmed.sorted/ --only-vocs BBB
2021-09-10 13:33:18 Begin
2021-09-10 13:33:18 Loading reads from bams/7601_2107902_09_S31.mapped.primertrimmed.sorted.bam
2021-09-10 13:33:40 Searching for reference signature mutations
2021-09-10 13:41:23 Searching for BBB signature mutations
2021-09-10 13:49:25 Formatting and writing reports
2021-09-10 13:49:25 Formatting summary
Traceback (most recent call last):
  File "/pub28/ibseq/miniconda2/envs/mmmvi/bin/mmmvi", line 10, in <module>
    sys.exit(main())
  File "/pub28/ibseq/miniconda2/envs/mmmvi/lib/python3.8/site-packages/mmmvi/mmmvi.py", line 121, in main
    reporting.write_reports(mutation_results, vocs, reads, args.outdir, args.delimiter)
  File "/pub28/ibseq/miniconda2/envs/mmmvi/lib/python3.8/site-packages/mmmvi/lib/reporting.py", line 541, in write_reports
    write_summary(voc_results, vocs, reads, outdir, delimiter)
  File "/pub28/ibseq/miniconda2/envs/mmmvi/lib/python3.8/site-packages/mmmvi/lib/reporting.py", line 485, in write_summary
    summary = format_summary(voc_results, vocs, reads)
  File "/pub28/ibseq/miniconda2/envs/mmmvi/lib/python3.8/site-packages/mmmvi/lib/reporting.py", line 80, in format_summary
    max_coverage = theoretical_maximum(reads, vocs)
  File "/pub28/ibseq/miniconda2/envs/mmmvi/lib/python3.8/site-packages/mmmvi/lib/reporting.py", line 168, in theoretical_maximum
    position_ranges = sorted(vocs[voc].keys())
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by dorbarker** [comment]
Hello ibseq,
I just fixed this yesterday. Updating to version `0.10.2` should do the trick. You can confirm your version with `mmmvi --version`
