### ISSUE TITLE
Output fails when using YAML files

### ISSUE THREAD

**Issue by melohar** [dorbarker/voc-identify#43]
Hi,

I am not getting any output files when using YAML files instead of a mutations file.  Please see error description below.

Thanks,

 melohar

2021-09-09 00:08:02 Begin
2021-09-09 00:08:02 Loading reads from SRR15291230_trimmed.bam
[E::idx_find_and_load] Could not retrieve index file for 'SRR15291230_trimmed.bam'
2021-09-09 00:08:03 Searching for reference signature mutations
2021-09-09 00:08:32 Searching for paragraph-footwork signature mutations
2021-09-09 00:08:40 Searching for slinky-antennae signature mutations
2021-09-09 00:08:48 Searching for perfume-sprint signature mutations
2021-09-09 00:08:56 Searching for cornstalk-handprint signature mutations
2021-09-09 00:09:02 Searching for spherical-trial signature mutations
2021-09-09 00:09:10 Searching for harbor-sprite signature mutations
2021-09-09 00:09:16 Searching for animating-thermos signature mutations
2021-09-09 00:09:24 Searching for empathy-serve signature mutations
2021-09-09 00:09:31 Searching for mushroom-android signature mutations
2021-09-09 00:09:39 Searching for carnival-shimmy signature mutations
2021-09-09 00:09:47 Searching for denture-daughter signature mutations
2021-09-09 00:09:55 Searching for marbling-doodle signature mutations
2021-09-09 00:10:01 Searching for unloved-crouton signature mutations
2021-09-09 00:10:07 Searching for dandelion-marshy signature mutations
2021-09-09 00:10:16 Searching for glorious-saucy signature mutations
2021-09-09 00:10:24 Searching for cheesy-styling signature mutations
2021-09-09 00:10:32 Searching for habitable-pasty signature mutations
2021-09-09 00:10:38 Searching for kelp-lesser signature mutations
2021-09-09 00:10:46 Formatting and writing reports
2021-09-09 00:10:46 Formatting summary
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/mmmvi", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mmmvi/mmmvi.py", line 134, in main
    reporting.write_reports(mutation_results, vocs, reads, args.outdir, args.delimiter)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mmmvi/lib/reporting.py", line 541, in write_reports
    write_summary(voc_results, vocs, reads, outdir, delimiter)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mmmvi/lib/reporting.py", line 485, in write_summary
    summary = format_summary(voc_results, vocs, reads)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mmmvi/lib/reporting.py", line 80, in format_summary
    max_coverage = theoretical_maximum(reads, vocs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mmmvi/lib/reporting.py", line 168, in theoretical_maximum
    position_ranges = sorted(vocs[voc].keys())
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by dorbarker** [comment]
Hi melohar, thanks for the bug report. There was an issue when dealing with indel mutations that somehow escaped earlier testing. Should be fixed now in version `0.10.2`
